# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
# Space + s で、カーソル下にある文字を検索、もしくは URL を開く
hook_add = '''
nmap <Space>s <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'egawata/sh-cmd-runner'
hook_add = '''
let g:sh_cmd_runner_cmd_prefix = '$ '
'''
