# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
# Space + s で、カーソル下にある文字を検索、もしくは URL を開く
hook_add = '''
nmap <Space>s <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'egawata/sh-cmd-runner'
hook_add = '''
let g:sh_cmd_runner_run_cmd_key = '<S-r>'
let g:sh_cmd_runner_cmd_prefix = '$ '
let g:sh_cmd_runner_result_separator = '~~~'
'''

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

# vim-lsp + 非同期入力補完
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_diagnostics_enabled = 0
  let g:lsp_log_verbose = 0
  " vim-lsp の定義ジャンプが利用できない場合は vim 本来のタグジャンプにフォールバックする
  nnoremap <expr> <silent> <C-]> execute(':LspDefinition') =~ "not supported" ? "\<C-]>" : ":echo<cr>"
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings_servers_dir = "~/.local/share/vim-lsp-settings/servers"
  nnoremap <C-]> :LspDefinition<CR>
  nnoremap <C-w>] :sp<CR>:LspDefinition<CR>
  nnoremap <C-w><C-]> :sp<CR>:LspDefinition<CR>
'''

# カッコ補完 foo -> (foo)
[[plugins]]
repo = 'machakann/vim-sandwich'

# Esc 押下後自動的に英数モードに切り替え
[[plugins]]
repo = 'brglng/vim-im-select'
hook_add = '''
    let g:im_select_default = 'com.google.inputmethod.Japanese.Roman'
'''

# gctags
# f 今のファイルの関数などの一覧
# j カーソル下の単語が含まれるタグの表示
# d カーソル下の単語の参照元を表示
# c カーソル下の単語の参照先を表示
[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
nnoremap <silent> <Space>f :Gtags -f %<CR>
nnoremap <silent> <Space>j :GtagsCursor<CR>
nnoremap <silent> <Space>d :<C-u>exe('Gtags '.expand('<cword>'))<CR>
nnoremap <silent> <Space>c :<C-u>exe('Gtags -r '.expand('<cword>'))<CR>
'''

# <leader>j でカーソル下単語の定義を探す
[[plugins]]
repo = 'pechorin/any-jump.vim'

# バッファを切り替える
# C-p で起動、C-j, C-k で選択切り替え
# 通常入力で検索語句を入力
# C-f でそのバッファへ移動
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# fzf
# <leader>+f で起動
[[plugins]]
repo = 'junegunn/fzf'
hook_add = '''
nnoremap <Leader>f :<C-u>FZF<CR>
'''
