# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
# Space + s で、カーソル下にある文字を検索、もしくは URL を開く
hook_add = '''
nmap <Space>s <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'egawata/sh-cmd-runner'
hook_add = '''
let g:sh_cmd_runner_cmd_prefix = '$ '
'''

[[plugins]]
repo = 'glidenote/memolist.vim'

# vim-lsp + 非同期入力補完
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# カッコ補完 foo -> (foo)
[[plugins]]
repo = 'machakann/vim-sandwich'

# Esc 押下後自動的に英数モードに切り替え
[[plugins]]
repo = 'brglng/vim-im-select'
hook_add = '''
    let g:im_select_default = 'com.google.inputmethod.Japanese.Roman'
'''

# <leader>j でカーソル下単語の定義を探す
[[plugins]]
repo = 'pechorin/any-jump.vim'
